### ISSUE TITLE
Error about webpack mox

### ISSUE THREAD

**Issue by ohakubi** [anindya-dhruba/laravel-vue-spa#15]
when I do npm run an error popping up. 

Error: Cannot find module 'mypath/node_modules/laravel-mix/setup/webpack.config.js'

**Comment by anindya-dhruba** [comment]
Please run `npm install` before running `npm run watch` or anything related to `npm`.

Note: 
Follow the [installation guide](https://github.com/anindya-dhruba/laravel-vue-spa#installation).

Hope it works.

**Comment by ohakubi** [comment]
of course I done it first :) I'm not that newbie. But i got the that error... Maybe I made some mistake about the installation step...

1) clone the repo into server
2) cd repo
3) install the app by composer
4) generate the key. (because it was not created by automatically) I see the home page on the browser without a problem. 
5) npm install, there is some issue about this part. because I have an error like below

✖ Error: pngquant failed to build, make sure that libpng-dev is installed

But installed npm. 

6) npm run watch. 

Error: Cannot find module 'mypath/node_modules/laravel-mix/setup/webpack.config.js'

my step of installation is wrong or something. 

Thank you.

**Comment by anindya-dhruba** [comment]
Hmm,
Looks like your OS is missing a Linux package. I found [this](https://github.com/imagemin/imagemin-pngquant/issues/46#issuecomment-379604951). I am not sure if it will solve your problem, but let's have a try.

Let me know the update.

**Comment by ohakubi** [comment]
okay, I very much solve the problem. thank you for concern. It was about the version of the `libpng-dev` 

And by the way. in the SPA there was not register page(only login). Do you consider update project with the register page? Because it's really nice project good folder structure. easy to understand. I want to learn/see how register page deploy in vue SPA.

**Comment by anindya-dhruba** [comment]
Glad to hear that it resolved your problem.

I would love to update this project, but I can't manage enough time to do so. You might see some PHP and node packages are outdated because I can't actively continue working on this. 

You are highly appreciated to update those and make a PR that will keep this repo up to date.

Thank you.
