### ISSUE TITLE
Case-sensitivity issues compiling

### ISSUE THREAD

**Issue by tristansnowsill** [anindya-dhruba/laravel-vue-spa#3]
Just cloned on Linux Ubuntu. All fine running composer install and npm install, but npm run dev fails with the following:

    These relative modules were not found:

    * ./components/Home/Home.vue in ./resources/assets/js/routes.js
    * ./components/Login/Login.vue in ./resources/assets/js/routes.js`

Fixed by changing ./resources/assets/js/routes.js to refer to ./components/home/Home.vue and ./components/login/Login.vue (note using lower case in corrected version). Haven't ever done GitHub pull request, so putting in as an issue as I'm not brave enough!

Love the package, thanks for all your hard work on it.

**Comment by anindya-dhruba** [comment]
Hi @tristansnowsill,
Thanks for the bug report. Really appreciate that. I will fix it after official release of Laravel 5.5.
