### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by lukeajtodd** [anindya-dhruba/laravel-vue-spa#5]
Hi,

Tried serving the site over HTTP using Valet and I was getting CORS errors upon trying to log in and then when serving it securely I get a 'Blocked loading mixed active content "http://localhost/api/authenticate' error instead.

Everything seems to be working fine and it's probably something dumb that I'm doing wrong but any help would be appreciated!

Thanks,
Luke

**Comment by cesaramirez** [comment]
You probably have to change the **`APP_URL`** variable in your .env file file which by default is `http://localhost`, in the **`config.js`** file take that url to define the **`apiDomain`** that you use to make the requests with axios.

**Comment by anindya-dhruba** [comment]
Hi @lukeajtodd , @cesaramirez 's approach should solve the problem. Reopen the issue is you still face the problem.
Thank you @cesaramirez

**Comment by lukeajtodd** [comment]
Thanks for the help! All sorted! :)
