### ISSUE TITLE
Problem when i login in

### ISSUE THREAD

**Issue by daferso93** [anindya-dhruba/laravel-vue-spa#9]
Hi, 
When i login in i can not see the Profile tab in up menu, and when go to Home tab and go again to login the app does do anything, u can help me please, if i get something wrong with my init configuration.

Thanks.

![image](https://user-images.githubusercontent.com/8727673/40333637-b73707b6-5d16-11e8-8834-88347d6497b3.png)

**Comment by anindya-dhruba** [comment]
Hello @daferso93,
I see you already closed the issue. Could you solve the issue or need any help?

Thanks.

**Comment by daferso93** [comment]
Hi, 

I can solve the problem, one cuestion what is the best way to manage Role & permision in vue & laravel. 

Thnks for the answer.

**Comment by drizzersilverberg** [comment]
@daferso93 you can use https://github.com/cartalyst/sentinel. if you having problem learning how to use sentinel, I suggest to observe the opinionated implementation https://github.com/SRLabs/Centaur
